export const CITIES_NAMES = [
  'arauca',
  'armenia',
  'barranquilla',
  'bogotá',
  'bucaramanga',
  'cali',
  'cartagena',
  'cúcuta',
  'florencia',
  'ibagué',
  'leticia',
  'manizales',
  'medellín',
  'mitú',
  'mocoa',
  'montería',
  'neiva',
  'pasto',
  'pereira',
  'popayán',
  'puerto carreño',
  'puerto inírida',
  'quibdo',
  'riohacha',
  'san andrés',
  'san jose del guaviare',
  'santa marta',
  'sincelejo',
  'tunja',
  'valledupar',
  'villavicencio',
  'yopal',
];
